<package format="2">
  <name>stationlite</name>
  <version>1.0.0</version>
  <description>Lumos Station Lite dual-arm robot description package.</description>

  <author>TODO</author>
  <maintainer email="todo@example.com">TODO</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>roslaunch</exec_depend>
  <exec_depend>rviz</exec_depend>

  <export>
    <architecture_independent />
  </export>
</package>
